### ISSUE TITLE
Consider using bracket-lib for rendering

### ISSUE THREAD

**Issue by erlend-sh** [jmdejong/rustifarm#1]
I saw the previous iteration of this was ascii-based so I assume you're planning to go down the same path for this Rust port. Please check out [bracket-lib](https://github.com/thebracket/bracket-lib).

We're trying to establish some convergence in the landscape of text-based game tooling. Your demonstration of multiplayer could be very useful to a lot of Rust gamedev learners.

**Comment by jmdejong** [comment]
I am currently only rewriting the server of the project.
The server does not do any rendering.
This project still uses the old python client.

I don't have any intention to rewrite the client at this moment.
Since this is an open source project anyone is free to create a new client using bracket-lib.
The documentation for the communication protocol is a bit outdated, but if you want to build a client I could update it.

I will keep bracket-lib in mind for other ascii games
